networks:
  app-network:
    driver: bridge

services:
  # 1. Nginx Gateway
  nginx:
    build:
      context: .
      dockerfile: infrastructure/nginx/Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    env_file: ./.env
    networks:
      - app-network
    depends_on:
      web-app:
        condition: service_started
      api:
        condition: service_healthy
    restart: unless-stopped

  # 2. Database
  db-main:
    image: postgres:18.3-alpine
    container_name: db-main-simshop
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Web-app (Next.js)
  web-app:
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: web-app
    expose:
      - "3000"
    env_file:
      - ./.env
      - ./apps/web-app/.env
    networks:
      - app-network
    user: root
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 50s
    depends_on:
      db-main:
        condition: service_healthy
    restart: always
  # 4. Migration Service
  api-migrate:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api-migrate
    env_file:
      - ./.env
      - ./apps/api/.env
    environment:
      - DB_HOST=db-main
    networks:
      - app-network
    volumes:
      - ./apps/api:/var/www/html
    # Chạy migration và dọn dẹp cache trước khi API chạy
    command: >
      sh -c "php artisan migrate --force && 
             php artisan cache:clear && 
             php artisan config:cache"
    depends_on:
      db-main:
        condition: service_healthy

  # 5. API (Laravel)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    expose:
      - "9000"
    env_file:
      - ./.env
      - ./apps/api/.env
    environment:
      - DB_HOST=db-main
    networks:
      - app-network
    command: ["php-fpm"]
    volumes:
      - ./apps/api:/var/www/html
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db-main:
        condition: service_healthy
      api-migrate:
        condition: service_completed_successfully
    restart: always

volumes:
  pgdata:
