user  nginx;
worker_processes  auto; # Tự động tối ưu theo số nhân CPU

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024; # Số kết nối đồng thời trên mỗi worker
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Tối ưu truyền tải file
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;

    # Bật Gzip để nén dữ liệu, giảm tải cho mạng và tăng tốc độ tải trang
    gzip  on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
    gzip_min_length 1000;

    # Nạp các cấu hình Routing từ thư mục conf.d
    include /etc/nginx/conf.d/*.conf;
}